### ISSUE TITLE
Hey, I refactor this component to a pure react component and make it easy to use!

### ISSUE THREAD

**Issue by flyingant** [jianliaoim/react-lite-audio#9]
Hey there,

Thanks for this amazing component. In the last days, I found this component could be a good choice in my project, but it looks not clearly enough to implement code as a react component. Then I refactor the whole project as a pure react component with 'ES6' and 'ESLint'. 
Now you guys can check the code on [github](https://www.npmjs.com/package/react-tiny-audio-player), also I published another version on  [npmjs](https://www.npmjs.com/package/react-tiny-audio-player).

Great thanks for this idea!!

Liu

**Comment by Boshen** [comment]
Nice ;-) Thank you for letting us know.
